openapi: 3.0.1
info:
  description: "Endpoints for interacting with files in the CMS Developer File System.\
    \ These files include HTML templates, CSS, JS, modules, and other assets which\
    \ are used to create CMS content."
  title: CMS Source Code
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: Endpoints which interact with actual file contents.
  name: Content
- description: Endpoints which interact with the object metadata for files.
  name: Metadata
- description: Endpoints used to validate developer asset files.
  name: Validation
- name: Source_Code_Extract
- name: Extract
paths:
  /cms/v3/source-code/extract/async:
    post:
      operationId: post-/cms/v3/source-code/extract/async_doAsync
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/FileExtractRequest'
        required: true
      responses:
        "202":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskLocator'
          description: accepted
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      tags:
      - Source_Code_Extract
  /cms/v3/source-code/extract/async/tasks/{taskId}/status:
    get:
      operationId: "get-/cms/v3/source-code/extract/async/tasks/{taskId}/status_getAsyncStatus"
      parameters:
      - explode: false
        in: path
        name: taskId
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ActionResponse'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      tags:
      - Source_Code_Extract
  /cms/v3/source-code/extract/{path}:
    post:
      deprecated: true
      description: Extracts a zip file in the file system. The zip file will be extracted
        in-place and not be deleted automatically.
      operationId: "post-/cms/v3/source-code/extract/{path}_extractByPath"
      parameters:
      - description: The file system location of the zip file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Extracts a zip file
      tags:
      - Extract
  /cms/v3/source-code/{environment}/content/{path}:
    delete:
      description: Deletes the file at the specified path in the specified environment.
      operationId: "delete-/cms/v3/source-code/{environment}/content/{path}_archive"
      parameters:
      - description: The environment of the file ("draft" or "published").
        explode: false
        in: path
        name: environment
        required: true
        schema:
          type: string
        style: simple
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Delete a file
      tags:
      - Content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    get:
      description: Downloads the byte contents of the file at the specified path in
        the specified environment.
      operationId: "get-/cms/v3/source-code/{environment}/content/{path}_get"
      parameters:
      - description: The environment of the file ("draft" or "published").
        explode: false
        in: path
        name: environment
        required: true
        schema:
          type: string
        style: simple
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      responses:
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Download a file
      tags:
      - Content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    post:
      deprecated: true
      description: Creates a file at the specified path in the specified environment.
        Accepts multipart/form-data content type. Throws an error if a file already
        exists at the specified path.
      operationId: "post-/cms/v3/source-code/{environment}/content/{path}_create"
      parameters:
      - description: The environment of the file ("draft" or "published").
        explode: false
        in: path
        name: environment
        required: true
        schema:
          type: string
        style: simple
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/put__cms_v3_source_code__environment__content__path__replace_request'
      responses:
        "200":
          content:
            application/json:
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Create a file
      tags:
      - Content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    put:
      description: Upserts a file at the specified path in the specified environment.
        Accepts multipart/form-data content type.
      operationId: "put-/cms/v3/source-code/{environment}/content/{path}_replace"
      parameters:
      - description: The environment of the file ("draft" or "published").
        explode: false
        in: path
        name: environment
        required: true
        schema:
          type: string
        style: simple
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/put__cms_v3_source_code__environment__content__path__replace_request'
      responses:
        "200":
          content:
            application/json:
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Create or update a file
      tags:
      - Content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /cms/v3/source-code/{environment}/metadata/{path}:
    get:
      description: Gets the metadata object for the file at the specified path in
        the specified environment.
      operationId: "get-/cms/v3/source-code/{environment}/metadata/{path}_get"
      parameters:
      - description: The environment of the file ("draft" or "published").
        explode: false
        in: path
        name: environment
        required: true
        schema:
          type: string
        style: simple
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Get the metadata for a file
      tags:
      - Metadata
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /cms/v3/source-code/{environment}/validate/{path}:
    post:
      description: Validates the file contents passed to the endpoint given a specified
        path and environment. Accepts multipart/form-data content type.
      operationId: "post-/cms/v3/source-code/{environment}/validate/{path}_doValidate"
      parameters:
      - description: The file system location of the file.
        explode: false
        in: path
        name: path
        required: true
        schema:
          pattern: .+
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/post__cms_v3_source_code__environment__validate__path__doValidate_request'
      responses:
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - content
      summary: Validate the contents of a file
      tags:
      - Validation
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    ActionResponse:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        status: PENDING
      properties:
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        completedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
      required:
      - completedAt
      - startedAt
      - status
      type: object
    AssetFileMetadata:
      description: The object metadata of a file.
      example:
        createdAt: 6
        archivedAt: 1
        folder: true
        children:
        - children
        - children
        name: name
        id: id
        updatedAt: 0
      properties:
        id:
          description: The path of the file in the CMS Developer File System.
          type: string
        name:
          description: The name of the file.
          type: string
        folder:
          description: Determines whether or not this path points to a folder.
          type: boolean
        children:
          description: "If the object is a folder, contains the filenames of the files\
            \ within the folder."
          items:
            type: string
          type: array
        updatedAt:
          description: Timestamp of when the object was last updated.
          format: int32
          type: integer
        createdAt:
          description: Timestamp of when the object was first created.
          format: int32
          type: integer
        archivedAt:
          description: Timestamp of when the object was archived (deleted).
          format: int64
          type: integer
      required:
      - createdAt
      - folder
      - id
      - name
      - updatedAt
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        category:
          description: The error category
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
          type: object
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
      required:
      - category
      - correlationId
      - message
      type: object
    ErrorDetail:
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
      required:
      - message
      type: object
    FileExtractRequest:
      example:
        path: path
      properties:
        path:
          type: string
      required:
      - path
      type: object
    TaskLocator:
      example:
        links:
          key: links
        id: id
      properties:
        id:
          type: string
        links:
          additionalProperties:
            type: string
          type: object
      required:
      - id
      type: object
    put__cms_v3_source_code__environment__content__path__replace_request:
      properties:
        file:
          description: The file to upload.
          format: binary
          type: string
    post__cms_v3_source_code__environment__validate__path__doValidate_request:
      properties:
        file:
          description: The file to validate.
          format: binary
          type: string
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            content: Read from and write to my Content
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
