openapi: 3.0.1
info:
  title: CMS Source Code
  description: "Endpoints for interacting with files in the CMS Developer File System.\
    \ These files include HTML templates, CSS, JS, modules, and other assets which\
    \ are used to create CMS content."
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Content
  description: Endpoints which interact with actual file contents.
- name: Metadata
  description: Endpoints which interact with the object metadata for files.
- name: Validation
  description: Endpoints used to validate developer asset files.
- name: Extract
paths:
  /cms/v3/source-code/extract/{path}:
    post:
      tags:
      - Extract
      summary: Extracts a zip file
      description: Extracts a zip file in the file system. The zip file will be extracted
        in-place and not be deleted automatically.
      operationId: "post-/cms/v3/source-code/extract/{path}"
      parameters:
      - name: path
        in: path
        description: The file system location of the zip file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      responses:
        "204":
          description: No content
          content: {}
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
  /cms/v3/source-code/{environment}/content/{path}:
    get:
      tags:
      - Content
      summary: Download a file
      description: Downloads the byte contents of the file at the specified path in
        the specified environment.
      operationId: "get-/cms/v3/source-code/{environment}/content/{path}"
      parameters:
      - name: environment
        in: path
        description: The environment of the file ("draft" or "published").
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      responses:
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    put:
      tags:
      - Content
      summary: Create or update a file
      description: Upserts a file at the specified path in the specified environment.
        Accepts multipart/form-data content type.
      operationId: "put-/cms/v3/source-code/{environment}/content/{path}"
      parameters:
      - name: environment
        in: path
        description: The environment of the file ("draft" or "published").
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/content_path_body'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    post:
      tags:
      - Content
      summary: Create a file
      description: Creates a file at the specified path in the specified environment.
        Accepts multipart/form-data content type. Throws an error if a file already
        exists at the specified path.
      operationId: "post-/cms/v3/source-code/{environment}/content/{path}"
      parameters:
      - name: environment
        in: path
        description: The environment of the file ("draft" or "published").
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/content_path_body_1'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      deprecated: true
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    delete:
      tags:
      - Content
      summary: Delete a file
      description: Deletes the file at the specified path in the specified environment.
      operationId: "delete-/cms/v3/source-code/{environment}/content/{path}"
      parameters:
      - name: environment
        in: path
        description: The environment of the file ("draft" or "published").
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      responses:
        "204":
          description: No content
          content: {}
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /cms/v3/source-code/{environment}/metadata/{path}:
    get:
      tags:
      - Metadata
      summary: Get the metadata for a file
      description: Gets the metadata object for the file at the specified path in
        the specified environment.
      operationId: "get-/cms/v3/source-code/{environment}/metadata/{path}"
      parameters:
      - name: environment
        in: path
        description: The environment of the file ("draft" or "published").
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetFileMetadata'
              example:
                id: /example.json
                name: example.json
                folder: false
                children: []
                updatedAt: 1608049506
                createdAt: 1608049506
                archivedAt: 0
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /cms/v3/source-code/{environment}/validate/{path}:
    post:
      tags:
      - Validation
      summary: Validate the contents of a file
      description: Validates the file contents passed to the endpoint given a specified
        path and environment. Accepts multipart/form-data content type.
      operationId: "post-/cms/v3/source-code/{environment}/validate/{path}"
      parameters:
      - name: path
        in: path
        description: The file system location of the file.
        required: true
        style: simple
        explode: false
        schema:
          pattern: .+
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/validate_path_body'
      responses:
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  schemas:
    AssetFileMetadata:
      required:
      - createdAt
      - folder
      - id
      - name
      - updatedAt
      type: object
      properties:
        id:
          type: string
          description: The path of the file in the CMS Developer File System.
        name:
          type: string
          description: The name of the file.
        folder:
          type: boolean
          description: Determines whether or not this path points to a folder.
        children:
          type: array
          description: "If the object is a folder, contains the filenames of the files\
            \ within the folder."
          items:
            type: string
        updatedAt:
          type: integer
          description: Timestamp of when the object was last updated.
          format: int32
        createdAt:
          type: integer
          description: Timestamp of when the object was first created.
          format: int32
        archivedAt:
          type: integer
          description: Timestamp of when the object was archived (deleted).
          format: int64
      description: The object metadata of a file.
      example:
        createdAt: 6
        archivedAt: 1
        folder: true
        children:
        - children
        - children
        name: name
        id: id
        updatedAt: 0
    Error:
      required:
      - category
      - correlationId
      - message
      type: object
      properties:
        message:
          type: string
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
        correlationId:
          type: string
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          format: uuid
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category:
          type: string
          description: The error category
        subCategory:
          type: string
          description: A specific category that contains more specific detail about
            the error
        errors:
          type: array
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
        context:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
        links:
          type: object
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
    ErrorDetail:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: A human readable message describing the error along with remediation
            steps where appropriate
        in:
          type: string
          description: The name of the field or parameter in which the error was found.
        code:
          type: string
          description: The status code associated with the error detail
        subCategory:
          type: string
          description: A specific category that contains more specific detail about
            the error
        context:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
    content_path_body:
      properties:
        file:
          type: string
          description: The file to upload.
          format: binary
    content_path_body_1:
      properties:
        file:
          type: string
          description: The file to upload.
          format: binary
    validate_path_body:
      properties:
        file:
          type: string
          description: The file to validate.
          format: binary
  responses:
    Error:
      description: An error occurred.
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    oauth2_legacy:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            content: Read from and write to my Content
    hapikey:
      type: apiKey
      name: hapikey
      in: query
