openapi: 3.0.1
info:
  description: Use this endpoint to query audit logs of CMS changes that occurred
    on your HubSpot account.
  title: CMS Audit Logs
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Audit_Logs
paths:
  /cms/v3/audit-logs/:
    get:
      description: Returns audit logs based on filters.
      operationId: get-/cms/v3/audit-logs/_getPage
      parameters:
      - description: Comma separated list of object ids to filter by.
        explode: true
        in: query
        name: objectId
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Comma separated list of user ids to filter by.
        explode: true
        in: query
        name: userId
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Timestamp after which audit logs will be returned
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: Timestamp before which audit logs will be returned
        explode: true
        in: query
        name: before
        required: false
        schema:
          type: string
        style: form
      - description: The sort direction for the audit logs. (Can only sort by timestamp).
        explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Comma separated list of event types to filter by (CREATED, UPDATED,
          PUBLISHED, DELETED, UNPUBLISHED).
        explode: true
        in: query
        name: eventType
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: The number of logs to return.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Comma separated list of object types to filter by (BLOG, LANDING_PAGE,
          DOMAIN, HUBDB_TABLE etc.)
        explode: true
        in: query
        name: objectType
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponsePublicAuditLog'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - content
      summary: Query audit logs
      tags:
      - Audit_Logs
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    CollectionResponsePublicAuditLog:
      description: The collection of audit logs.
      example:
        paging:
          next:
            link: link
            after: after
        results:
        - objectName: My Landing Page
          fullName: John Doe
          event: UPDATED
          userId: "1011561"
          objectId: "4065364319"
          timestamp: "1583792674672"
          objectType: LANDING_PAGE
        - objectName: My Landing Page
          fullName: John Doe
          event: UPDATED
          userId: "1011561"
          objectId: "4065364319"
          timestamp: "1583792674672"
          objectType: LANDING_PAGE
      properties:
        results:
          items:
            $ref: '#/components/schemas/PublicAuditLog'
          type: array
        paging:
          $ref: '#/components/schemas/Paging'
      required:
      - results
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        category:
          description: The error category
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
          type: object
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
      required:
      - category
      - correlationId
      - message
      type: object
    ErrorDetail:
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
      required:
      - message
      type: object
    NextPage:
      example:
        link: link
        after: after
      properties:
        after:
          type: string
        link:
          type: string
      required:
      - after
      type: object
    Paging:
      example:
        next:
          link: link
          after: after
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    PublicAuditLog:
      example:
        objectName: My Landing Page
        fullName: John Doe
        event: UPDATED
        userId: "1011561"
        objectId: "4065364319"
        timestamp: "1583792674672"
        objectType: LANDING_PAGE
      properties:
        objectId:
          description: The ID of the object.
          type: string
        userId:
          description: The ID of the user who caused the event.
          type: string
        timestamp:
          description: The timestamp at which the event occurred.
          format: date-time
          type: string
        objectName:
          description: The internal name of the object in HubSpot.
          type: string
        fullName:
          description: The name of the user who caused the event.
          type: string
        event:
          description: The type of event that took place (CREATED, UPDATED, PUBLISHED,
            DELETED, UNPUBLISHED).
          enum:
          - CREATED
          - UPDATED
          - PUBLISHED
          - DELETED
          - UNPUBLISHED
          type: string
        objectType:
          description: The type of the object (BLOG, LANDING_PAGE, DOMAIN, HUBDB_TABLE
            etc.)
          enum:
          - BLOG
          - BLOG_POST
          - LANDING_PAGE
          - WEBSITE_PAGE
          - TEMPLATE
          - MODULE
          - GLOBAL_MODULE
          - SERVERLESS_FUNCTION
          - DOMAIN
          - URL_MAPPING
          - EMAIL
          - CONTENT_SETTINGS
          - HUBDB_TABLE
          - KNOWLEDGE_BASE_ARTICLE
          - KNOWLEDGE_BASE
          - THEME
          - CSS
          - JS
          type: string
      required:
      - event
      - fullName
      - objectId
      - objectName
      - objectType
      - timestamp
      - userId
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            content: Read from and write to my Content
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
