openapi: 3.0.1
info:
  description: "Subscriptions allow contacts to control what forms of communications\
    \ they receive. Contacts can decide whether they want to receive communication\
    \ pertaining to a specific topic, brand, or an entire HubSpot account."
  title: Subscriptions
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: Whether a contact has subscribed or unsubscribed from a given subscription
    type.
  name: Status
- description: The different subscription types that are defined in a portal.
  name: Definition
paths:
  /communication-preferences/v3/definitions:
    get:
      description: Get a list of all subscription definitions for the portal
      operationId: get-/communication-preferences/v3/definitions_getPage
      responses:
        "200":
          content:
            application/json:
              example:
                subscriptionDefinitions:
                - id: "1805677"
                  name: Default HubSpot Blog Subscription
                  description: Receive timely updates with the latest blog posts.
                  isActive: true
                  isDefault: false
                  isInternal: false
                  createdAt: 2019-08-05T13:01:15.875Z
                  updatedAt: 2019-08-05T13:01:15.875Z
                - id: "1805669"
                  name: Customer Service Communication
                  description: Receive feedback requests and customer service information.
                  purpose: Service
                  communicationMethod: Email
                  isActive: true
                  isDefault: true
                  isInternal: true
                  createdAt: 2019-08-05T13:01:15.875Z
                  updatedAt: 2019-08-05T13:01:15.875Z
                - id: "1805670"
                  name: One to One
                  description: One to One emails
                  purpose: Sales
                  communicationMethod: Email
                  isActive: true
                  isDefault: true
                  isInternal: true
                  createdAt: 2019-08-05T13:01:15.875Z
                  updatedAt: 2019-08-05T13:01:15.875Z
              schema:
                $ref: '#/components/schemas/SubscriptionDefinitionsResponse'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - communication_preferences.read_write
      - oauth2_legacy:
        - communication_preferences.read
      summary: Get subscription definitions
      tags:
      - Definition
  /communication-preferences/v3/status/email/{emailAddress}:
    get:
      description: Returns a list of subscriptions and their status for a given contact.
      operationId: "get-/communication-preferences/v3/status/email/{emailAddress}_getEmailStatus"
      parameters:
      - explode: false
        in: path
        name: emailAddress
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                recipient: example@example.com
                subscriptionStatuses:
                - id: "7148714"
                  name: Default HubSpot Blog Subscription
                  description: Receive timely updates with the latest blog posts.
                  status: SUBSCRIBED
                  sourceOfStatus: SUBSCRIPTION_STATUS
                  preferenceGroupName: Initial Group
                  legalBasis: CONSENT_WITH_NOTICE
                  legalBasisExplanation: "At users request, we opted them in"
                - id: "7148715"
                  name: One to One
                  description: One to One emails
                  status: NOT_SUBSCRIBED
                  sourceOfStatus: SUBSCRIPTION_STATUS
                  legalBasis: CONSENT_WITH_NOTICE
                  legalBasisExplanation: User has requested to be opted out
              schema:
                $ref: '#/components/schemas/PublicSubscriptionStatusesResponse'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - hapikey: []
      - oauth2_legacy:
        - communication_preferences.read_write
      - oauth2_legacy:
        - communication_preferences.read
      summary: Get subscription statuses for a contact
      tags:
      - Status
  /communication-preferences/v3/subscribe:
    post:
      description: Subscribes a contact to the given subscription type. This API is
        not valid to use for subscribing a contact at a brand or portal level and
        will return an error.
      operationId: post-/communication-preferences/v3/subscribe_subscribe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicUpdateSubscriptionStatusRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                id: "7148714"
                name: Default HubSpot Blog Subscription
                description: Receive timely updates with the latest blog posts.
                status: SUBSCRIBED
                sourceOfStatus: SUBSCRIPTION_STATUS
                preferenceGroupName: Initial Group
                legalBasis: CONSENT_WITH_NOTICE
                legalBasisExplanation: "At users request, we opted them in"
              schema:
                $ref: '#/components/schemas/PublicSubscriptionStatus'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - communication_preferences.write
      - hapikey: []
      - oauth2_legacy:
        - communication_preferences.read_write
      summary: Subscribe a contact
      tags:
      - Status
  /communication-preferences/v3/unsubscribe:
    post:
      description: Unsubscribes a contact from the given subscription type. This API
        is not valid to use for unsubscribing a contact at a brand or portal level
        and will return an error.
      operationId: post-/communication-preferences/v3/unsubscribe_unsubscribe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicUpdateSubscriptionStatusRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                id: "7148714"
                name: Default HubSpot Blog Subscription
                description: Receive timely updates with the latest blog posts.
                status: NOT_SUBSCRIBED
                sourceOfStatus: SUBSCRIPTION_STATUS
                preferenceGroupName: Initial Group
                legalBasis: CONSENT_WITH_NOTICE
                legalBasisExplanation: "At users request, we opted them out"
              schema:
                $ref: '#/components/schemas/PublicSubscriptionStatus'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2_legacy:
        - communication_preferences.write
      - hapikey: []
      - oauth2_legacy:
        - communication_preferences.read_write
      summary: Unsubscribe a contact
      tags:
      - Status
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    ErrorDetail:
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
      required:
      - message
      type: object
    PublicUpdateSubscriptionStatusRequest:
      description: A request to change the status of a contact's subscription.
      example:
        emailAddress: emailAddress
        legalBasis: LEGITIMATE_INTEREST_PQL
        subscriptionId: subscriptionId
        legalBasisExplanation: legalBasisExplanation
      properties:
        emailAddress:
          description: Contact's email address.
          type: string
        subscriptionId:
          description: ID of the subscription being updated for the contact.
          type: string
        legalBasis:
          description: Legal basis for updating the contact's status (required for
            GDPR enabled portals).
          enum:
          - LEGITIMATE_INTEREST_PQL
          - LEGITIMATE_INTEREST_CLIENT
          - PERFORMANCE_OF_CONTRACT
          - CONSENT_WITH_NOTICE
          - NON_GDPR
          - PROCESS_AND_STORE
          - LEGITIMATE_INTEREST_OTHER
          type: string
        legalBasisExplanation:
          description: A more detailed explanation to go with the legal basis (required
            for GDPR enabled portals).
          type: string
      required:
      - emailAddress
      - subscriptionId
      type: object
    PublicSubscriptionStatusesResponse:
      description: A collection of subscription statuses for a contact.
      example:
        recipient: recipient
        subscriptionStatuses:
        - brandId: 0
          name: name
          description: description
          legalBasis: LEGITIMATE_INTEREST_PQL
          preferenceGroupName: preferenceGroupName
          id: id
          legalBasisExplanation: legalBasisExplanation
          status: SUBSCRIBED
          sourceOfStatus: PORTAL_WIDE_STATUS
        - brandId: 0
          name: name
          description: description
          legalBasis: LEGITIMATE_INTEREST_PQL
          preferenceGroupName: preferenceGroupName
          id: id
          legalBasisExplanation: legalBasisExplanation
          status: SUBSCRIBED
          sourceOfStatus: PORTAL_WIDE_STATUS
      properties:
        recipient:
          description: Email address of the contact.
          type: string
        subscriptionStatuses:
          description: A list of all of the contact's subscriptions statuses.
          items:
            $ref: '#/components/schemas/PublicSubscriptionStatus'
          type: array
      required:
      - recipient
      - subscriptionStatuses
      type: object
    SubscriptionDefinitionsResponse:
      description: A collection of subscription definitions for the portal.
      example:
        subscriptionDefinitions:
        - isInternal: true
          createdAt: 2000-01-23T04:56:07.000+00:00
          isDefault: true
          communicationMethod: communicationMethod
          purpose: purpose
          name: name
          description: description
          id: id
          isActive: true
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - isInternal: true
          createdAt: 2000-01-23T04:56:07.000+00:00
          isDefault: true
          communicationMethod: communicationMethod
          purpose: purpose
          name: name
          description: description
          id: id
          isActive: true
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        subscriptionDefinitions:
          description: A list of all subscription definitions.
          items:
            $ref: '#/components/schemas/SubscriptionDefinition'
          type: array
      required:
      - subscriptionDefinitions
      type: object
    SubscriptionDefinition:
      example:
        isInternal: true
        createdAt: 2000-01-23T04:56:07.000+00:00
        isDefault: true
        communicationMethod: communicationMethod
        purpose: purpose
        name: name
        description: description
        id: id
        isActive: true
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          description: The ID of the definition.
          type: string
        name:
          description: The name of the subscription.
          type: string
        description:
          description: A description of the subscription.
          type: string
        purpose:
          description: The purpose of this subscription or the department in your
            organization that uses it.
          type: string
        communicationMethod:
          description: The method or technology used to contact.
          type: string
        isActive:
          description: Whether the definition is active or archived.
          type: boolean
        isDefault:
          description: A subscription definition created by HubSpot.
          type: boolean
        isInternal:
          description: A default description that is used by some HubSpot tools and
            cannot be edited.
          type: boolean
        createdAt:
          description: Time at which the definition was created.
          format: date-time
          type: string
        updatedAt:
          description: Time at which the definition was last updated.
          format: date-time
          type: string
      required:
      - createdAt
      - description
      - id
      - isActive
      - isDefault
      - isInternal
      - name
      - updatedAt
      type: object
    PublicSubscriptionStatus:
      description: The status of a subscription for a contact.
      example:
        brandId: 0
        name: name
        description: description
        legalBasis: LEGITIMATE_INTEREST_PQL
        preferenceGroupName: preferenceGroupName
        id: id
        legalBasisExplanation: legalBasisExplanation
        status: SUBSCRIBED
        sourceOfStatus: PORTAL_WIDE_STATUS
      properties:
        id:
          description: The ID for the subscription.
          type: string
        name:
          description: The name of the subscription.
          type: string
        description:
          description: A description of the subscription.
          type: string
        status:
          description: Whether the contact is subscribed.
          enum:
          - SUBSCRIBED
          - NOT_SUBSCRIBED
          type: string
        sourceOfStatus:
          description: Where the status is determined from e.g. PORTAL_WIDE_STATUS
            if the contact opted out from the portal.
          enum:
          - PORTAL_WIDE_STATUS
          - BRAND_WIDE_STATUS
          - SUBSCRIPTION_STATUS
          type: string
        brandId:
          description: "The ID of the brand that the subscription is associated with,\
            \ if there is one."
          format: int64
          type: integer
        preferenceGroupName:
          description: The name of the preferences group that the subscription is
            associated with.
          type: string
        legalBasis:
          description: The legal reason for the current status of the subscription.
          enum:
          - LEGITIMATE_INTEREST_PQL
          - LEGITIMATE_INTEREST_CLIENT
          - PERFORMANCE_OF_CONTRACT
          - CONSENT_WITH_NOTICE
          - NON_GDPR
          - PROCESS_AND_STORE
          - LEGITIMATE_INTEREST_OTHER
          type: string
        legalBasisExplanation:
          description: A more detailed explanation to go with the legal basis.
          type: string
      required:
      - description
      - id
      - name
      - sourceOfStatus
      - status
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        category:
          description: The error category
          type: string
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
          type: object
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
      required:
      - category
      - correlationId
      - message
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            communication_preferences.read: Read contact subscription preferences
            communication_preferences.read_write: Update contact subscription preferences
            communication_preferences.write: Update contact subscription preferences
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
x-hubspot-available-client-libraries:
- Python
- Ruby
