openapi: 3.0.1
info:
  title: CMS Performance API
  description: Use these endpoints to get a time series view of your website's performance.
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Public_Performance
paths:
  /cms/v3/performance/:
    get:
      tags:
      - Public_Performance
      summary: View your website's performance.
      description: Returns time series data website performance data for the given
        domain and/or path.
      operationId: get-/cms/v3/performance/_getPage
      parameters:
      - name: domain
        in: query
        description: The domain to search return data for.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: path
        in: query
        description: The url path of the domain to return data for.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: pad
        in: query
        description: Specifies whether the time series data should have empty intervals
          if performance data is not present to create a continuous set.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: sum
        in: query
        description: Specifies whether the time series data should be summated for
          the given period. Defaults to false.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: period
        in: query
        description: "A relative period to return time series data for. This value\
          \ is ignored if start and/or end are provided. Valid periods: [15m, 30m,\
          \ 1h, 4h, 12h, 1d, 1w]"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: interval
        in: query
        description: "The time series interval to group data by. Valid intervals:\
          \ [1m, 5m, 15m, 30m, 1h, 4h, 12h, 1d, 1w]"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: start
        in: query
        description: A timestamp in milliseconds that indicates the start of the time
          period.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: end
        in: query
        description: A timestamp in milliseconds that indicates the end of the time
          period.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicPerformanceResponse'
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
  /cms/v3/performance/uptime:
    get:
      tags:
      - Public_Performance
      summary: View your website's uptime.
      description: Returns uptime time series website performance data for the given
        domain.
      operationId: get-/cms/v3/performance/uptime_getUptime
      parameters:
      - name: domain
        in: query
        description: The domain to search return data for.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: path
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: pad
        in: query
        description: Specifies whether the time series data should have empty intervals
          if performance data is not present to create a continuous set.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: sum
        in: query
        description: Specifies whether the time series data should be summated for
          the given period. Defaults to false.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: period
        in: query
        description: "A relative period to return time series data for. This value\
          \ is ignored if start and/or end are provided. Valid periods: [15m, 30m,\
          \ 1h, 4h, 12h, 1d, 1w]"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: interval
        in: query
        description: "The time series interval to group data by. Valid intervals:\
          \ [1m, 5m, 15m, 30m, 1h, 4h, 12h, 1d, 1w]"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: start
        in: query
        description: A timestamp in milliseconds that indicates the start of the time
          period.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: end
        in: query
        description: A timestamp in milliseconds that indicates the end of the time
          period.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicPerformanceResponse'
        default:
          description: An error occurred.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - hapikey: []
components:
  schemas:
    Error:
      required:
      - category
      - correlationId
      - message
      type: object
      properties:
        message:
          type: string
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
        correlationId:
          type: string
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          format: uuid
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category:
          type: string
          description: The error category
        subCategory:
          type: string
          description: A specific category that contains more specific detail about
            the error
        errors:
          type: array
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
        context:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Context about the error condition
          example:
            invalidPropertyName:
            - propertyValue
            missingScopes:
            - scope1
            - scope2
        links:
          type: object
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
    ErrorDetail:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: A human readable message describing the error along with remediation
            steps where appropriate
        in:
          type: string
          description: The name of the field or parameter in which the error was found.
        code:
          type: string
          description: The status code associated with the error detail
        subCategory:
          type: string
          description: A specific category that contains more specific detail about
            the error
        context:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
    PerformanceView:
      required:
      - 100X
      - 20X
      - 30X
      - "403"
      - "404"
      - 40X
      - "500"
      - "504"
      - 50X
      - 50th
      - 95th
      - 99th
      - avgOriginResponseTime
      - cacheHitRate
      - cacheHits
      - endDatetime
      - endTimestamp
      - responseTimeMs
      - startDatetime
      - startTimestamp
      - totalRequestTime
      - totalRequests
      type: object
      properties:
        startTimestamp:
          type: integer
          description: The timestamp in milliseconds of the start of this interval.
          format: int64
        endTimestamp:
          type: integer
          description: The timestamp in milliseconds of the end of this interval.
          format: int64
        startDatetime:
          type: string
        endDatetime:
          type: string
        totalRequests:
          type: integer
          description: The total number of requests received in this period.
          format: int32
        cacheHits:
          type: integer
          description: The total number of requests that were served cached responses.
          format: int32
        cacheHitRate:
          type: number
          description: The percentage of requests that were served cached responses.
        totalRequestTime:
          type: integer
          format: int32
        avgOriginResponseTime:
          type: integer
          description: The average response time in milliseconds from the origin to
            the edge.
          format: int32
        responseTimeMs:
          type: integer
          description: The average response time in milliseconds.
          format: int32
        "100X":
          type: integer
          description: The number of responses that had an http status code between
            1000-1999.
          format: int32
        "20X":
          type: integer
          description: The number of responses that had an http status code between
            200-299.
          format: int32
        "30X":
          type: integer
          description: The number of responses that had an http status code between
            300-399.
          format: int32
        "40X":
          type: integer
          description: The number of responses that had an http status code between
            400-499.
          format: int32
        "50X":
          type: integer
          description: The number of responses that had an http status code between
            500-599.
          format: int32
        "403":
          type: integer
          description: The number of responses that had an http status code of 403.
          format: int32
        "404":
          type: integer
          description: The number of responses that had an http status code of 404.
          format: int32
        "500":
          type: integer
          description: The number of responses that had an http status code of 500.
          format: int32
        "504":
          type: integer
          description: The number of responses that had an http status code of 504.
          format: int32
        "50th":
          type: integer
          description: The 50th percentile response time.
          format: int32
        "95th":
          type: integer
          description: The 95th percentile response time.
          format: int32
        "99th":
          type: integer
          description: The 99th percentile response time.
          format: int32
      description: An individual time series performance data point.
      example:
        startDatetime: startDatetime
        responseTimeMs: 9
        "95th": 4
        totalRequests: 1
        cacheHitRate: 5.637376656633329
        "99th": 5
        totalRequestTime: 2
        "100X": 3
        "500": 6
        "403": 1
        "50th": 1
        "404": 1
        cacheHits: 5
        "504": 7
        "20X": 2
        "30X": 4
        "40X": 7
        endTimestamp: 6
        "50X": 1
        startTimestamp: 0
        endDatetime: endDatetime
        avgOriginResponseTime: 7
    PublicPerformanceResponse:
      required:
      - data
      - endInterval
      - interval
      - startInterval
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PerformanceView'
        domain:
          type: string
        path:
          type: string
        startInterval:
          type: integer
          format: int64
        endInterval:
          type: integer
          format: int64
        interval:
          type: string
          enum:
          - ONE_MINUTE
          - FIVE_MINUTES
          - TEN_MINUTES
          - FIFTEEN_MINUTES
          - THIRTY_MINUTES
          - ONE_HOUR
          - FOUR_HOURS
          - TWELVE_HOURS
          - ONE_DAY
          - ONE_WEEK
        period:
          type: string
          enum:
          - ONE_MINUTE
          - FIVE_MINUTES
          - TEN_MINUTES
          - FIFTEEN_MINUTES
          - THIRTY_MINUTES
          - ONE_HOUR
          - FOUR_HOURS
          - TWELVE_HOURS
          - ONE_DAY
          - ONE_WEEK
      example:
        path: path
        period: ONE_MINUTE
        data:
        - startDatetime: startDatetime
          responseTimeMs: 9
          "95th": 4
          totalRequests: 1
          cacheHitRate: 5.637376656633329
          "99th": 5
          totalRequestTime: 2
          "100X": 3
          "500": 6
          "403": 1
          "50th": 1
          "404": 1
          cacheHits: 5
          "504": 7
          "20X": 2
          "30X": 4
          "40X": 7
          endTimestamp: 6
          "50X": 1
          startTimestamp: 0
          endDatetime: endDatetime
          avgOriginResponseTime: 7
        - startDatetime: startDatetime
          responseTimeMs: 9
          "95th": 4
          totalRequests: 1
          cacheHitRate: 5.637376656633329
          "99th": 5
          totalRequestTime: 2
          "100X": 3
          "500": 6
          "403": 1
          "50th": 1
          "404": 1
          cacheHits: 5
          "504": 7
          "20X": 2
          "30X": 4
          "40X": 7
          endTimestamp: 6
          "50X": 1
          startTimestamp: 0
          endDatetime: endDatetime
          avgOriginResponseTime: 7
        startInterval: 9
        domain: domain
        interval: ONE_MINUTE
        endInterval: 9
  responses:
    Error:
      description: An error occurred.
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    hapikey:
      type: apiKey
      name: hapikey
      in: query
